### PR TITLE
Process and Thread Manipulation

### PR DESCRIPTION
**Pull request by awsmhacks**
I'm hoping to add some new tasks to Covenant and have the need to suspend/resume processes. 
I didn't see any current functionality to do this and decided to bake into SharpSploit. 
Also added code for killing processes even though you wrote a short task to do so in covenant already, figured it might be useful here.  

These can (and I probably will) be expanded upon to better reflect the current Shell methods. i.e. adding cred params to the function.
  
This PR adds:  
[-] 2 methods of killing a process (by name or PID).  
[-] Ability to Suspend a Process
[-] Ability to Resume a Process
[-] 3 new signatures for PInvoke Win32
     ---SuspendThread
     ---ResumeThread
     ---TerminateThread

  
  

demo app
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SharpSploit;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            SharpSploit.Execution.Shell shell = new SharpSploit.Execution.Shell();

            string suspendOut = SharpSploit.Execution.Shell.SuspendProcess("SomeProcName");
            Console.WriteLine(suspendOut);

            var a = Console.ReadKey(); // to pause

            string resumeOut = SharpSploit.Execution.Shell.ResumeProcess("SomeProcName");
            Console.WriteLine(resumeOut);

            a = Console.ReadKey(); // to pause

            string killOut = SharpSploit.Execution.Shell.KillProcessByName("SomeProcName");
            Console.WriteLine(killOut);

            a = Console.ReadKey(); // to pause
        }
    }
}
```

### CODE REVIEW

**Comment by checkymander** [comment]
Think it would make sense for these to take a Process ID rather than a process name? The current implementation seems like it would take out multiple processes if they were all running the same name (e.g. svchost, rundll32, chrome).  I think specify process ID would be more opsec safe.

**Comment by awsmhacks** [comment]
I did add a method to kill by PID but didn't provide an example. 
use via    
SharpSploit.Execution.Shell. KillProcessById(ProcId);

Or did you mean for suspend/resume?
I can add methods for suspend/resume using just a PID as well.

**Comment by checkymander** [comment]
Yeah I meant for the suspend/resume. Change the functions to take an ID rather than a name, and let the caller/task figure out how it wants to handle getting said ID of the process. Also I think Sharpsploit.Execution.Shell is the wrong place for this, I've never been great at figuring out the best places for some of the functions haha, but it might make more sense in Sharpsploit.Execution.Injection namespace, since some of the other thread handling stuff is there.

**Comment by awsmhacks** [comment]
word, i'll whip those up tomorrow and maybe add some test cases for them.  
  
And yeah, wasn't exactly sure where these fit best, almost went with something like process and thread extension classes in misc.utilities.  idk.  
So within Injection as its own class? piece into executiontechnique somewhere? or what exactly were you thinking

**Comment by awsmhacks** [comment]
Suspend/Resume are now:
--SuspendProcessByName()
--SuspendProcessById()
--ResumeProcessByName()
--ResumeProcessById()

**Comment by cobbr** [comment]
Sorry for the delay on this one @awsmhacks , thanks for the contribution!

**Pull request merged**
