### PR TITLE
+Native Dinvoke Wrappers

### PR DESCRIPTION
**Pull request by FuzzySecurity**
I added 3 new wrappers for Dinvoke:

+ **RtlZeroMemory**: To null memory you alloc, for example with AllocHGlobal.
+ **ProcessWow64Information**: Nt way of determining if a process is x32 on x64 OS, returns true or false.
+ **ProcessBasicInformation**: Return a PROCESS_BASIC_INFORMATION struct for a process.

### CODE REVIEW

**Comment by FuzzySecurity** [comment]
Btw note that we already have a pinvoke definition for NtQueryInformationProcess and an enum for the information classes.

https://github.com/cobbr/SharpSploit/blob/master/SharpSploit/Execution/Win32.cs#L1294

The slightly unfortunate part is that the pinvoke definition is hard coded for "ProcessBasicInformation". If there are no objections I'll modify that to be generic as well so we can use all information classes and make a small change here where it is used in the project.

https://github.com/cobbr/SharpSploit/blob/master/SharpSploit/Enumeration/Host.cs#L122

**Comment by rasta-mouse** [comment]
@FuzzySecurity that's stuff I added, feel free to modify 🙂

**Comment by FuzzySecurity** [comment]
Ty Sir, I'll update and amend my pull request 👍

**Comment by FuzzySecurity** [comment]
@rasta-mouse have a look, it's just a minor change. Instead of ref struct, you have IntPtr so no matter which information class you want you can use NtQueryInformationProcess generically.

**Comment by FuzzySecurity** [comment]
I added 3 more wrappers for Dinvoke:

+ NtOpenProcess
+ NtQueueApcThread
+ NtOpenThread

There is more to add but I will hold for now until someone can review the pull request to see if there are any formal issues to take care of 👍

**Comment by cobbr** [comment]
Fantastic work @FuzzySecurity!

One thing I wonder about is the use of the enum/structures from the Win32.cs file built for the P/Invoke signatures.

Does it make more sense to couple your D/Invoke work to that library or to duplicate the enums/structures within the `SharpSploit.Execution.DynamicInvoke` namespace? Do you or @TheWover have any opinions on that?

**Comment by FuzzySecurity** [comment]
@cobbr & @TheWover dealers choice, I'm happy to move it around 👍. My reasoning was to avoid duplication, it gives people a central place to look for API data

**Comment by cobbr** [comment]
I think we landed on separating the enums/structs from the functions, and sharing the enums/structs between `PlatformInvoke` and `DynamicInvoke`.

Separated those out and merged! Thanks again @FuzzySecurity 🙂

**Pull request merged**
