### PR TITLE
Updated Mimikatz loader and version, removed deprecated PE class

### PR DESCRIPTION
**Pull request by TheWover**
Updated the Mimikatz loader to use the new Manual Mapping API. While I was at it, I built the latest version of mimikatz (2.2.0 #19041 Jun 16 2020 19:17:38) and updated that in the SharpSploit resources. Should add a few months worth of features.

Since the PE class is now obsolete, I removed it. There is now a PE class in Execution.ManualMap that contains the PE data structures necessary for manually mapping PEs.

NOTE: Do not merge this until we can fix the Manual Mapping API to support WOW64 processes. I think I may know the issue, but haven't quite fixed it yet.

image

### CODE REVIEW

**Comment by TheWover** [comment]
Updated to improve the mimikatz output. It now no longer manually marshalls strings as SafetyKatz did. It now uses managed strings instead.

**Comment by TheWover** [comment]
Updated to overload mimikatz into a copy of dbghelp.dll. This will ensure that the execution of mimikatz is happening from file-backed memory, appearing to be done from a module that normally performs debug-like actions.

**Comment by TheWover** [comment]
I figured out why module overloading didn't find a random file. There wasn't one large enough that met the requirement of having a legitimate signature. So I added an option to Module Overloading to not require that the decoy module be legitimately signed, then updated Mimikatz to use that. It will just pick a random DLL in `WINDIR\System32\`  that meets the size requirements. I also added an optional parameter to `Mimikatz.Command` that lets you specify the decoy module to load it into.

Also, Mimikatz can now bring you a cup of coffee. :coffee:

**Comment by TheWover** [comment]
Apparently the source branch was nuked. Remake this and re-PR.

**Comment by cobbr** [comment]
Closing, merged the other PR.

**Pull request closed without merging**
